### ISSUE TITLE
Support templating in the input string

### ISSUE THREAD

**Issue by sindresorhus** [chalk/chalk-cli#1]
To style text with multiple different style combinations without having to call the binary multiple times.

Example:

```
$ chalk '{blue.bold}unicorn{/blue.bold} {red}♥{/red}'
```

**Comment by Qix-** [comment]
I'll get 'er in a little.

**Comment by Qix-** [comment]
@sindresorhus do we want to keep the original functionality, or will this be breaking?

**Comment by sindresorhus** [comment]
I would prefer to keep the original functionality too. It's a lot simpler for the common case.

**Comment by Qix-** [comment]
So is

``` bash
chalk bold red '{blue}hi{/blue}'
```

the same as

``` bash
chalk '{bold.red}{blue}hi{/blue}{/bold.red}'
```

?

**Comment by sindresorhus** [comment]
They should be mutually exclusive.

**Comment by Qix-** [comment]
:+1:

**Comment by Qix-** [comment]
What about

```
chalk {bold.red this is a string that is now {blue blue}}.
```

**Comment by sindresorhus** [comment]
:+1:

**Comment by sindresorhus** [comment]
@Qix- Still interested in doing this one?

**Comment by Qix-** [comment]
Yeah I can do it. A lot of this has fallen off my radar with the job stuff going on D:

**Comment by sindresorhus** [comment]
Fixed by https://github.com/chalk/chalk-cli/commit/90fe7151908815969bb38721762ab7c380e5b6ac
