### ISSUE TITLE
Examples don’t work 

### ISSUE THREAD

**Issue by NightMachinery** [chalk/chalk-cli#12]
![745BFC77-D8EE-4666-AB2F-587297795341](https://user-images.githubusercontent.com/36224762/62830708-4b53af00-bc28-11e9-948f-1381e0ddd4a5.jpeg)

I just installed this via npm, so latest version.

**Comment by Qix-** [comment]
The screenshot looks correct to me. What's not working, specifically?

**Comment by NightMachinery** [comment]
The first command’s blue style is ignored.

**Comment by Qix-** [comment]
`~` means "not".

**Comment by NightMachinery** [comment]
@qix I know that. But shouldn't it be applied only to `bold`? After all, it is utterly stupid to negate the blue color as there was no blue color to begin with.

**Comment by Qix-** [comment]
Doesn't matter if it's stupid, it's operating correctly. The point was to show the function of the 'not' operator side by side.
