### ISSUE TITLE
Add flag -n for not printing a new line

### ISSUE THREAD

**Issue by NightMachinery** [chalk/chalk-cli#13]
Like `echo -n`.

**Comment by sindresorhus** [comment]
Why not just use `\n` in the string? Would be the same amount of characters.

**Comment by NightMachinery** [comment]
@sindresorhus The -n flag disables the newline. Current behavior adds a newline even without specifying `\n`.

**Comment by sindresorhus** [comment]
Ah ok. What's the use-case?

**Comment by NightMachinery** [comment]
@sindresorhus I needed it for creating a debugging utility that colored stuff to distinguish the word boundary.
It makes chalk composable. The current design forces one to invoke the tool once with the complete output.

**Comment by sindresorhus** [comment]
Alright. PR welcome. 👍
