### ISSUE TITLE
yosay together with chalk-cli

### ISSUE THREAD

**Issue by dimitrieh** [chalk/chalk-cli#3]
[yosay](https://github.com/yeoman/yosay) mentions _You can style your text with chalk before passing it to yosay._ 

however I can't get it to work with chalk-cli like:
`yosay chalk bold red "green"`
or
`chalk bold red "green" | yosay`

this is logical, but how can i get it to work?

**Comment by sindresorhus** [comment]
Coloring is disabled when piped. Use the `--color` flag to force it:
`chalk bold red "green" --color | yosay`

Or: `yosay $(chalk bold red "green" --color)`
