### ISSUE TITLE
Idea: Colorized help message

### ISSUE THREAD

**Issue by msabramo** [chalk/chalk-cli#34]
Inspired by https://github.com/ahmadawais/cli-meow-help and by the fact that `chalk-cli` is itself a colorizing tool, I wonder if the tool should have colorized help? 

Maybe something like this?

![Screen Shot 2021-09-14 at 11 14 52 AM](https://user-images.githubusercontent.com/305268/133312045-fa61d03d-6b28-417f-8faf-70ffed04a24f.png)

I can't decide if I like this.
On one hand, I love tools with color. Also, I think the "Examples" section is a particularly good place to use color to show the user what output they would get.
OTOH, it makes it a bit harder to read the help text when looking at the code in `cli.js`.
I could go either way.

Code for this: https://github.com/chalk/chalk-cli/compare/main...msabramo:help-colors?expand=1

Note: I tried out https://github.com/ahmadawais/cli-meow-help and it's probably very nice for a lot of CLI tools, but I think it didn't result in super-pleasing output for this tool, because some of the assumptions it make -- i.e.: CLIs that have multiple commands, flags have default values, etc.

![Screen Shot 2021-09-14 at 11 24 49 AM](https://user-images.githubusercontent.com/305268/133312921-d7ac388a-855f-498b-a711-9415adfa8b0d.png)

Code for this: https://github.com/chalk/chalk-cli/compare/main...msabramo:cli-meow-help?expand=1

**Comment by sindresorhus** [comment]
I usually find coloring help to not be necessary, but since `chalk-cli` is for coloring stuff, a colored help output would be nice.
